### ISSUE TITLE
Do you have some Benchmark stats ?

### ISSUE THREAD

**Issue by KabDeveloper** [dgtony/orderbook-rs#4]
Hi,

Do you have some benchmark for your order matching engine please ?

Thank you

**Comment by dgtony** [comment]
There is no benchmarks, because it was a just-for-fun project. Though current orderbook implementation is pretty fast, I'd not use it in the performance-critical production setting.
If you really care about latency, there is some room for improvements, e.g. fine tuning of core data structures with unsafe.

**Comment by KabDeveloper** [comment]
@dgtony Hi and thanks for your answer.

Do you mean improving the way you store data ? Optimize with fastest Hash Map ?

**Comment by dgtony** [comment]
I mean custom data structure for order queues, preallocated on the stack, instead of combination `(BinaryHeap; HashMap)`.

**Comment by KabDeveloper** [comment]
@dgtony Do you have any reference on GitHub or something in your mind that u will use in the futur or already thinking about ?

Thank you again
